# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.5

before_script:
    - travis_retry composer self-update
        - travis_retry composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit --verbose
